### PR TITLE
use propper verbage

### PR DESCRIPTION
**Pull request by paetling**
cc @thieman

### CODE REVIEW

**Comment by paetling** [comment]
ohh shit. I broke stuff. Gonna fix.  Also it seems like I need to push a fixed version to pypi.  Do I have access to do that?

**Comment by thieman** [comment]
I think you're fine, one of the test runs passed and the other had some sort of git trouble, maybe github had a blip or something. What's your PyPi username, I can add you to permissions.

**Comment by paetling** [comment]
paetling I believe

**Comment by thieman** [comment]
Added

**Pull request merged**
